# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrintWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrintWindow(object):
    def setupUi(self, PrintWindow):
        PrintWindow.setObjectName("PrintWindow")
        PrintWindow.resize(800, 600)
        PrintWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(PrintWindow)
        self.centralwidget.setObjectName("centralwidget")
        printer = QPrinter(QPrinter.HighResolution)
        self.widget = QPrintPreviewWidget(printer, self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(280, 110, 511, 461))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 409, 97))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 20, 261, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Icon/Media/Icons/Mega Logo.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        PrintWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PrintWindow)
        self.statusbar.setObjectName("statusbar")
        PrintWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PrintWindow)
        QtCore.QMetaObject.connectSlotsByName(PrintWindow)

    def retranslateUi(self, PrintWindow):
        _translate = QtCore.QCoreApplication.translate
        PrintWindow.setWindowTitle(_translate("PrintWindow", "MainWindow"))
        self.label.setText(_translate("PrintWindow", "Asistente de impresion"))
from PySide2.QtPrintSupport import QPrintPreviewWidget, QPrinter
import source_rc
